repositories:
  - name: stable
    url: https://charts.helm.sh/stable

  {{ if env "PLATFORM_HELM_CHART_REPO_URL" }}
  # Platform chart repo - currently not used but we may want to bring charts inhouse
  - name: "platform-chart-repo"
    url: '{{ env "PLATFORM_HELM_CHART_REPO_URL" }}'
  {{ end }}

releases:
  - name: eks-core-cluster-autoscaler
    namespace: kube-system
    chart: stable/cluster-autoscaler
    values:
    - "../environments/mgmt/HelmValuesNPE/cluster-autoscaler.yaml"

  - name: eks-core-nginx-ingress-ext
    namespace: kube-system
    chart: stable/nginx-ingress
    values:
    - "../environments/mgmt/HelmValuesNPE/nginx-ingress-ext.yaml"

  - name: eks-core-external-dns
    namespace: kube-system
    chart: stable/external-dns
    values:
    - "../environments/mgmt/HelmValuesNPE/external-dns.yaml"

  # SDP Support tooling
  - name: weave-scope
    namespace: {{ env "SDP_TOOLING_NAMESPACE" | default "default" }}
    labels:
      component: sdp_support_tooling
    chart: stable/weave-scope
